---
- name: disable PolicyKit support in libvirtd
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    line: '{{item}}'
  with_items:
    -  ' '
    - '#recommend to disable PolicyKit support in libvirtd on RHEL/CentOS 7.x'
    - 'auth_unix_ro = "none"'
    - 'auth_unix_rw = "none"'
    - 'unix_sock_group = "oneadmin"'
    - 'unix_sock_ro_perms = "0770"'
    - 'unix_sock_rw_perms = "0770"'
  notify:
    - restart libvirtd
