---
- name: enable opennebula.repo
  template:
    src: "opennebula_repo.j2"
    dest: "/etc/yum.repos.d/opennebula.repo"
    owner: root
    group: root
    mode: 644

- name: Ensure some packages are installed
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ packages }}"
  when: packages is defined
  tags:
    - install

- name: Run install_gems
  shell: "sudo su - -c '/usr/share/one/install_gems --yes'"
