---
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: set timezone
  timezone:
    name: "{{ time_zone }}"

- name: create hosts file
  copy:
    src: "etc_host"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 644
