---
- name: Ensure all services running
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: "{{ services }}"
  when: services is defined
  tags:
    - services

- name: Ensure start some sockets
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items: "{{ sockets }}"
  when: sockets is defined
  tags:
    - sockets
